runtime: python39
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: flask
  version: 3.0.3
- name: tensorflow
  version: 2.15.0
- name: keras
  version: 2.15.0